apiVersion: 1

providers:
  - name: "UPS Dashboards"
    folder: "UPS"
    folderUid: "nut"
    type: file
    editable: true
    disableDeletion: false
    updateIntervalSeconds: 10
    options:
      path: /etc/grafana/provisioning/dashboards/nut
      foldersFromFilesStructure: false
